name: Brew Test & Build Bottles

on:
  push:
    branches:
      - master
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test-bot:
    strategy:
      matrix:
        os: [macos-14, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - name: Run brew test-bot (--only-cleanup-before)
        run: brew test-bot --only-cleanup-before

      - name: Run brew test-bot (--only-setup)
        run: brew test-bot --only-setup

      - name: Run brew test-bot (--only-tap-syntax)
        run: brew test-bot --only-tap-syntax

      - name: Run brew test-bot (--only-formulae)
        run: |
          brew test-bot --only-formulae --root-url=https://ghcr.io/v2/couchbaselabs/couchbase couchbase-cxx-client
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Job Summary
        if: always()
        run: |
          FORMULA=$(basename Formula/*.rb .rb)
          VERSION=$(grep -E '^\s*url\s' "Formula/${FORMULA}.rb" | sed -E 's/.*-([0-9]+\.[0-9]+\.[0-9]+)\.tar.*/\1/')
          cat << EOF >> "$GITHUB_STEP_SUMMARY"
          ### 🍺 Bottle Build Details

          * **Formula**: \`${FORMULA}\` (Version ${VERSION})
          * **GitHub Package Container Page**: https://github.com/orgs/couchbaselabs/packages/container/package/couchbase%2F${FORMULA}
          * **Exact OCI Image Reference**: \`ghcr.io/couchbaselabs/couchbase/${FORMULA}:${VERSION}\`
          * **OCI Manifest Endpoint**: \`https://ghcr.io/v2/couchbaselabs/couchbase/${FORMULA}/manifests/${VERSION}\`
          EOF

      - name: Upload bottles as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bottles_${{ matrix.os }}
          path: '*.bottle.*'
